#ifndef ENUM_H
#define ENUM_H

enum ERROR_FUNCTION {
    GOOD_WORKING  = 0,
    ERROR_CALLOC  = 1,
    ERROR_REALLOC = 2,
};

enum LIST_ERROR {
    LIST_ERROR_POINTER_STRUCT_NULL        = 1 << 0,
    LIST_ERROR_POINTER_BUFFER_VALUE_NULL  = 1 << 1,
    LIST_ERROR_POINTER_BUFFER_NEXT_NULL   = 1 << 2,
    LIST_ERROR_POINTER_BUFFER_PREV_NULL   = 1 << 3,
    LIST_ERROR_SIZE_SMALLER_ZERO          = 1 << 4,
    LIST_ERROR_CAPACITY_SMALLER_ZERO      = 1 << 5,
    LIST_ERROR_SIZE_BIGGER_CAPACITY       = 1 << 6,
    LIST_ERROR_HEAD_BIGGER_CAPACITY       = 1 << 7,
    LIST_ERROR_TAIL_BIGGER_CAPACITY       = 1 << 8,

};

#endif // ENUM_H